---
title: "PPT_with_officer"
author: "Arush Mohan"
date: "`r Sys.Date()`"
output: html_document
---


## Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(ggrepel)
library(lubridate)
library(readxl)
library(officer)
library(gt)

# Reading in the data from an excel file
data <- read_excel("data/DID_data_22-24.xlsx")

# Ingesting the ppt template with ICS branding

template_presentation <- read_pptx('input/template.pptx') 

```



## Data Wrangling
```{r}

# In this example, the data has already been cleaned and organised in a 'tidy' format. 


# Modify the column names
data <- data %>%
  rename_all(~ tolower(gsub(" ", "_", .)))

```


## Building the PPT


### SLIDE 1: Add a title slide


```{r}

Presentation <- template_presentation %>%
  add_slide(layout = "No Image_Date/name multiple lines", master = "Presentation Title Slides") %>%
  ph_with(my_pres, value = "Presentation Building Workshop", location = ph_location_type(type = "title"))
```



### SLIDE 2: Adding the context section slide


```{r}

# Adding a section title slide

Presentation <- template_presentation %>%
  add_slide(layout = "Style 1", master = "Section Slide") %>%
  ph_with(my_pres, value = "Context", location = ph_location_label(ph_label = "Text Placeholder 6"))
```


### SLIDE 3: Adding Context

```{r}
# Adding th context slide with content

Presentation <- template_presentation %>%
  add_slide(layout = "One Column", master = "Content Slide White") %>%
  ph_with(value = "Context", location = ph_location_label(ph_label = "Title 1")) %>% 
  ph_with(value = block_list(
  fpar(ftext("Introduction to officer", prop = fp_text(bold = TRUE))),
  fpar(ftext("Creating Slides", prop = fp_text())),
  fpar(ftext("Adding Content", prop = fp_text(italic = TRUE)))
), location = ph_location_label(ph_label = "Content Placeholder 2"))

```


## Visualisations

### SLIDE 4: Modalities


```{r}

plot <- ggplot(data, aes(x = modality)) +
  geom_bar(fill = "#005EB8") +
  labs(title = "Distribution of Modalities", x = "Modality", y = "Activity")


```

### Summary table

```{r}

summary_data <- data %>%
  group_by(modality) %>%
  summarize(avg_imd_rank = mean(as.numeric(imd_rank_decile), na.rm = TRUE))

print(summary_data)

```


### MSK vs Non - MSK proportion

```{r}

# create a bar chart comparing the msk vs non- msk activity

plot<- ggplot(data, aes(x = msk_flag)) +
  geom_bar(aes(y = ..prop.., group = 1), fill = "#005EB8") +
  labs(title = "Proportion of MSK vs Non-MSK Cases", x = "MSK Flag", y = "Proportion")

print(plot)
```



### Boxplot imd rank deciles by modalites

```{r}
# Create summary table that shows the average IMD Rank Decile by Modality and MSK Flag - use gt to format the table 


plot <- ggplot(data, aes(x = modality, y = as.numeric(imd_rank_decile))) +
  geom_boxplot(fill = "lightgreen") +
  labs(title = "IMD Rank Decile by Modality", x = "Modality", y = "IMD Rank Decile")

print(plot)

```


### CCG Activity


```{r}
# total activity per CCG

ggplot(data, aes(x = ccg_name)) +
  geom_bar(fill = "purple") +
  labs(title = "Activity by CCG", x = "CCG Name", y = "Activity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```


###

```{r}


```

## Creating the ppt output


```{r}

Presentation %>%
  print(target = paste0('output/PPT_workshop.pptx'))

```


## PPT Reference Layout

```{r}


layouts <- layout_summary(template_presentation)

print_placeholders <- function(layout_name, master_name){
  placeholders <- layout_properties(template_presentation, layout = layout_name, master = master_name)
  print(paste("PLaceholders:", layout_name, master_name))
  print(placeholders)
}

walk2(.x = layouts$layout, .y = layouts$master, ~print_placeholders(.x, .y))

```